defmodule CassWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cass

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # The session only ever carries an opaque, random session token (never a user
  # id and never an authorization decision), and it is HttpOnly so scripts
  # cannot read it. `SameSite=Lax` is what makes the session survive ordinary
  # top-level navigation from another site while still blocking cross-site
  # POSTs, which is what the CSRF token is there to catch. The cookie is marked
  # `secure` in production (`:secure_cookies`, see `config/prod.exs`), which is
  # required by Phoenix to protect against a session fixation attack over plain
  # HTTP.
  @session_options [
    store: :cookie,
    key: "_cass_key",
    signing_salt: "swgMDDOm",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:cass, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :cass,
    gzip: not code_reloading?,
    only: CassWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :cass
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CassWeb.Router
end
