defmodule Cass.Payments do
  @moduledoc """
  The Payments boundary: collecting an order's server-derived total through a
  provider-agnostic payment pipeline.

  This module owns the payment lifecycle — the only code allowed to create a
  payment, advance its status, or pay an order. Everything behind it is plain
  data in, plain verdicts out. It resolves the configured provider adapter
  (`Cass.Payments.Provider`), talks to it through the behaviour, and does all
  persistence.

  ## Invariants

    * **Money is never invented here.** `amount_cents`/`currency` are
      snapshotted from the order inside the boundary; a provider is only ever
      asked to collect exactly `order.total_cents` in `order.currency`, and a
      webhook/verify result whose amount or currency disagrees with the
      snapshot is refused outright — the order is never paid.
    * **Idempotency.** `provider_reference` is generated by CASS *before* the
      provider is contacted and passed through as the provider's custom
      reference. Re-initializing an order with a live (`:pending`/`:processing`)
      attempt returns that attempt's checkout URL. A duplicate success webhook
      is a no-op. The `(provider, provider_reference)` partial unique index is
      the database-level guard.
    * **The boundary is the only writer.** A provider adapter never touches the
      database or `Cass.Orders`; this module advances payment and order status,
      serializing `payment → :succeeded` + `Cass.Orders.mark_order_paid/1` in a
      single transaction so an order can never be `:paid` while its payment is
      not `:succeeded`, nor the other way around.
    * **No transaction across a network call.** A payment is created and
      finalized in short transactions; the provider is called between them. No
      database transaction ever waits on the provider.

  ## Status machine

  Transitions (see `Cass.Payments.Payment` for the vocabulary):

      pending    → processing | succeeded | failed | cancelled | expired
      processing → succeeded | failed | cancelled | expired
      succeeded  → succeeded (idempotent webhook) | refunded (reserved)
      failed/cancelled/expired/refunded → (terminal)

  ## Authorization

  `initialize_payment/3` resolves the order through `Cass.Orders.get_order/2`,
  so the same ownership rule as reading applies: an account pays only its own
  orders, an admin may initialize any order, and a foreign or unknown order id
  is `{:error, :not_found}` — indistinguishable from a missing one.

  Webhooks are deliberately outside the browser stack and authorize only by the
  provider's signature, verified inside each adapter (`parse_webhook/2`).
  """
  import Ecto.Query, warn: false

  alias Cass.Accounts.Scope
  alias Cass.Orders
  alias Cass.Orders.Order
  alias Cass.Payments.Payment
  alias Cass.Payments.Provider.CaptureResult
  alias Cass.Payments.Providers
  alias Cass.Repo

  @default_provider :paystack
  @payment_unavailable "payments are temporarily unavailable"

  @doc "Returns the closed vocabulary of payment statuses."
  defdelegate payment_statuses(), to: Payment, as: :statuses

  @doc """
  Returns a configured provider adapter for `name`, or `{:error, :unknown_provider}`.

  ## Examples

      iex> provider(:paystack)
      {:ok, Cass.Payments.Providers.Paystack}

      iex> provider(:stripe)
      {:error, :unknown_provider}

  """
  def provider(name), do: Providers.resolve(name)

  @doc """
  Starts (or resumes) payment for an order on behalf of `scope`.

  There are no money inputs: the amount and currency are the order's
  server-derived total, and the customer email is the order owner's
  (overridable via `:email`). The provider is picked from `opts[:provider]`
  (defaults to the first enabled one, `:paystack`).

  Returns `{:ok, %{payment:, order:, checkout_url:}}` so the caller can send
  the customer to the hosted checkout, or:

    * `{:error, :not_found}` — foreign, unknown, or malformed order id;
    * `{:error, changeset}` — the order is not awaiting payment, or the
      provider could not be reached (that attempt is recorded as `:failed`).

  Re-initializing an order that already has a live attempt returns that
  attempt's checkout URL without contacting the provider again, so double
  clicks and retries cannot spawn parallel sessions.
  """
  def initialize_payment(%Scope{} = scope, order_id, opts \\ []) do
    with {:ok, order} <- fetch_awaiting_order(scope, order_id),
         {:ok, module} <- resolve_provider(Keyword.get(opts, :provider, default_provider())) do
      email = Keyword.get(opts, :email, order.user.email)

      case active_payment_for(order.id) do
        %Payment{checkout_url: url} = payment when is_binary(url) ->
          {:ok, result(payment, order)}

        %Payment{} = payment ->
          run_provider_init(payment, order, module, email)

        nil ->
          case insert_pending(order, module) do
            {:ok, payment} -> run_provider_init(payment, order, module, email)
            {:error, changeset} -> {:error, changeset}
          end
      end
    end
  end

  @doc """
  Handles a provider webhook end to end.

  `provider` is the configured provider atom (`:paystack`), `raw_body` the raw
  request body, and `headers` the request headers as a map. The adapter verifies
  the payload's authenticity (signature), then the boundary reconciles the
  event against the payment snapshot.

  Returns `:ok` for accepted events (including irrelevant/ignored events and
  idempotent duplicates) or `{:error, reason}`. `:invalid_signature` is a
  client-refusable refusal; everything else (unknown reference, amount
  mismatch) is a server-side refusal reported generically.
  """
  def handle_webhook(provider, raw_body, headers) when is_binary(raw_body) do
    with {:ok, module} <- provider(provider),
         {:ok, event} <- module.parse_webhook(raw_body, headers) do
      reconcile(provider, event)
    end
  end

  ## Initialization internals

  defp fetch_awaiting_order(scope, order_id) do
    case Orders.get_order(scope, order_id) do
      nil ->
        {:error, :not_found}

      %Order{status: :awaiting_payment} = order ->
        {:ok, Repo.preload(order, :user)}

      %Order{} ->
        {:error, refusal("the order is not awaiting payment")}
    end
  end

  defp resolve_provider(name) do
    case Providers.resolve(name) do
      {:ok, module} -> {:ok, module}
      {:error, :unknown_provider} -> {:error, refusal(@payment_unavailable)}
    end
  end

  defp default_provider do
    case Providers.enabled() do
      [provider | _rest] -> provider
      [] -> @default_provider
    end
  end

  defp active_payment_for(order_id) do
    Repo.one(
      from p in Payment,
        where: p.order_id == ^order_id and p.status in [:pending, :processing],
        order_by: [desc: p.inserted_at],
        limit: 1
    )
  end

  defp insert_pending(order, module) do
    reference = generate_reference()

    changeset =
      %Payment{}
      |> Payment.changeset(%{
        provider: module.name() |> Atom.to_string(),
        provider_reference: reference,
        amount_cents: order.total_cents,
        currency: order.currency,
        status: :pending,
        metadata: %{}
      })
      |> Ecto.Changeset.put_change(:order_id, order.id)

    Repo.insert(changeset)
  end

  defp run_provider_init(payment, order, module, email) do
    with {:ok, init} <- provider_initialize(module, email, order, payment.provider_reference) do
      complete_initialization(payment, order, init)
    else
      {:error, reason} -> fail_initialization(payment, reason)
    end
  end

  defp provider_initialize(module, email, order, reference) do
    case module.initialize_payment(email, order.total_cents, order.currency, reference) do
      {:ok, %{checkout_url: url} = init} when is_binary(url) -> {:ok, init}
      {:ok, _missing_url} -> {:error, :missing_checkout_url}
      {:error, reason} -> {:error, reason}
    end
  end

  defp complete_initialization(payment, order, init) do
    changes = %{
      status: :processing,
      checkout_url: init.checkout_url,
      provider_reference: init.provider_reference || payment.provider_reference,
      expires_at: init.expires_at,
      metadata: Map.merge(payment.metadata || %{}, init.metadata || %{})
    }

    case update_payment(payment, changes) do
      {:ok, payment} -> {:ok, result(payment, order)}
      {:error, changeset} -> {:error, changeset}
    end
  end

  defp fail_initialization(payment, reason) do
    case update_payment(payment, %{status: :failed, failure_reason: reason_message(reason)}) do
      {:ok, _failed} -> {:error, refusal(@payment_unavailable)}
      {:error, changeset} -> {:error, changeset}
    end
  end

  defp result(payment, order) do
    %{payment: payment, order: order, checkout_url: payment.checkout_url}
  end

  ## Webhook reconciliation internals

  defp reconcile(_provider, :ignored), do: :ok

  defp reconcile(provider, %CaptureResult{} = event) do
    with {:ok, payment} <- find_by_reference(provider, event.provider_reference),
         {:ok, payment} <- guard_amount_and_currency(event, payment) do
      case transition_capture(payment, event) do
        {:ok, _payment} -> :ok
        {:error, _} = error -> error
      end
    end
  end

  defp find_by_reference(provider, reference) when is_binary(reference) and reference != "" do
    case Repo.one(
           from p in Payment,
             where: p.provider == ^Atom.to_string(provider) and p.provider_reference == ^reference
         ) do
      nil -> {:error, :unknown_payment}
      payment -> {:ok, payment}
    end
  end

  defp find_by_reference(_provider, _reference), do: {:error, :unknown_payment}

  # A verified capture with monetary details is cross-checked against the
  # snapshot before anything is paid; a mismatch means the capture is not for
  # the amount we asked for, and it is refused.
  defp guard_amount_and_currency(
         %{amount_cents: amount, currency: currency},
         %Payment{} = payment
       )
       when is_integer(amount) and is_binary(currency) do
    if amount == payment.amount_cents and currency == payment.currency do
      {:ok, payment}
    else
      {:error, :amount_mismatch}
    end
  end

  # Only the amount was described; check that much.
  defp guard_amount_and_currency(%{amount_cents: amount}, %Payment{} = payment)
       when is_integer(amount) do
    if amount == payment.amount_cents do
      {:ok, payment}
    else
      {:error, :amount_mismatch}
    end
  end

  defp guard_amount_and_currency(_event, %Payment{} = payment), do: {:ok, payment}

  # A duplicate success webhook is a no-op: the payment is already `:succeeded`
  # and its order already `:paid` (committed together below).
  defp transition_capture(%Payment{status: :succeeded} = payment, %{status: :succeeded}),
    do: {:ok, payment}

  defp transition_capture(%Payment{status: status} = payment, %{status: :succeeded} = event)
       when status in [:pending, :processing],
       do: mark_paid(payment, event)

  defp transition_capture(%Payment{status: status} = payment, %{status: event_status} = event)
       when status in [:pending, :processing] and event_status in [:failed, :cancelled],
       do: record_capture_failure(payment, event)

  defp transition_capture(_payment, _event), do: {:error, :invalid_transition}

  # The one place money changes hands on our side: the payment becomes
  # `:succeeded` and the order is marked `:paid` in a single transaction, so
  # either both commit or the whole capture is rolled back.
  defp mark_paid(%Payment{} = payment, %CaptureResult{} = event) do
    Repo.transact(fn ->
      changes = %{
        status: :succeeded,
        paid_at: event.paid_at,
        payment_method: Map.get(event.metadata || %{}, "channel"),
        metadata: Map.merge(payment.metadata || %{}, event.metadata || %{})
      }

      with {:ok, payment} <- update_payment(payment, changes),
           {:ok, _order} <- Orders.mark_order_paid(payment.order_id) do
        {:ok, payment}
      else
        {:error, _} = error -> error
      end
    end)
  end

  defp record_capture_failure(%Payment{} = payment, %{status: status} = event) do
    reason =
      case Map.get(event.metadata || %{}, "provider_status") do
        nil -> "payment was not completed"
        raw -> "provider reported #{raw}"
      end

    metadata = Map.merge(payment.metadata || %{}, event.metadata || %{})

    case update_payment(payment, %{status: status, failure_reason: reason, metadata: metadata}) do
      {:ok, payment} -> {:ok, payment}
      {:error, changeset} -> {:error, changeset}
    end
  end

  ## Shared internals

  defp update_payment(payment, changes) do
    payment
    |> Payment.changeset(changes)
    |> Repo.update()
  end

  defp generate_reference do
    "PY-" <> Base.encode32(:crypto.strong_rand_bytes(8), case: :upper, padding: false)
  end

  defp reason_message(%{__exception__: true} = exception) do
    exception
    |> Exception.message()
    |> String.slice(0, 500)
  end

  defp reason_message({:paystack_refused, message}) when is_binary(message),
    do: String.slice(message, 0, 500)

  defp reason_message(reason) when is_binary(reason), do: String.slice(reason, 0, 500)

  defp reason_message(reason), do: inspect(reason) |> String.slice(0, 500)

  defp refusal(message) do
    Ecto.Changeset.add_error(Ecto.Changeset.change(%Payment{}), :base, message)
  end
end
